### ISSUE TITLE
geometric standard deviation

### ISSUE THREAD

**Issue by kkiwimagi** [jakebeal/TASBEFlowAnalytics#1]
Why do you use 
s = 10.^std(log10(data));
instead of 
s = exp.^std(log(data));

for your geometric standard deviation calculation?

**Comment by jakebeal** [comment]
I believe that you actually mean 
s = exp(std(log(data)))

The two are equivalent, and we preferred to use log10 for simplicity in debugging.

**Comment by kkiwimagi** [comment]
Awesome thank you for your feedback.

**Comment by jakebeal** [comment]
This issue was moved to TASBE/TASBEFlowAnalytics#6
