### ISSUE TITLE
read_filtered_au

### ISSUE THREAD

**Issue by kkiwimagi** [jakebeal/TASBEFlowAnalytics#2]
function [data fcshdr] = read_filtered_au(CM,filename)
    % Get read FCS file and select channels of interest
    [fcsunscaled fcshdr rawfcs] = fca_readfcs(filename);

Did you mean?
 [rawfcs fcshdr] = fca_readfcs(filename);

**Comment by jakebeal** [comment]
No, this needs to be as it is: the "fcsunscaled" does not actually give a.u. values in some FCS usages.

**Comment by kkiwimagi** [comment]
First thank you very much for your quick reply.
What is your def for au?
Also why use fcsdat in other operations such as (fcs_scatter) but here use fcsdatscaled?
% [fcsdat, fcshdr, fcsdatscaled] = fca_readfcs(filename);
% Supplying the third output the fcsdatscaled array contains the scaled     
% parameters. It might be useful for logscaled parameters, but no effect 
% in the case of linear parameters. The log scaling is the following
% operation for the "ith" parameter:  
% fcsdatscaled(:,i) = ...
%   10.^(fcsdat(:,i)/fcshdr.par(i).range*fcshdr.par(i).decade;);

Also I did a comparison of data exported different ways and found that even the fcsdatscaled does not match exactly? Is this already accounted for in your code?
![image](https://cloud.githubusercontent.com/assets/27301942/25496811/54371960-2b50-11e7-9d78-6da93fa4918f.png)

Thank you for your help,
Katherine

**Comment by jakebeal** [comment]
This issue was moved to TASBE/TASBEFlowAnalytics#5
