### ISSUE TITLE
time_filter(fcshdr,rawfcs)

### ISSUE THREAD

**Issue by kkiwimagi** [jakebeal/TASBEFlowAnalytics#3]
Why would data collected during a FACs run be contaminated based on the time it was collected?

Thanks for your help,
Katherine

**Comment by jakebeal** [comment]
In some cases, there is sample-to-sample carryover or other transients in the initial portion of a flow cytometry run. We encountered with with Noah's data at times.

**Comment by kkiwimagi** [comment]
Awesome, thank you.

**Comment by jakebeal** [comment]
This issue was moved to TASBE/TASBEFlowAnalytics#7
