### ISSUE TITLE
make_linear_compensation_model -- neg Values from AF

### ISSUE THREAD

**Issue by kkiwimagi** [jakebeal/TASBEFlowAnalytics#4]
How do we know setting low values to 1 is not adding systematic error to the results? Would it be better to keep all data till the end?

% make sure nothing's below 1, for compensation and geometric statistics
% (compensation can be badly thrown off by negative values)
no_AF_data(no_AF_data<1) = 1;

Also if compensation is a linear model why would negative values throw it off?

Thank you again for your help,
Katherine

**Comment by jakebeal** [comment]
This issue was moved to TASBE/TASBEFlowAnalytics#3

**Comment by jakebeal** [comment]
This issue was moved to TASBE/TASBEFlowAnalytics#4
