### ISSUE TITLE
Undefined function 'getSetting' for input arguments of type 'matlab.settings.SettingsGroup'

### ISSUE THREAD

**Issue by bpteague** [jakebeal/TASBEFlowAnalytics#5]
When I try to run template_colormodel/make_color_model.m in TASBEFlowAnalytics-Tutorial, I get

    >> make_color_model
    Undefined function 'getSetting' for input arguments of type 'matlab.settings.SettingsGroup'.

    Error in autodetect_gating (line 17)
        output_path = getSetting(settings, 'path', './');

    Error in make_color_model (line 20)
    autogate = autodetect_gating(blankfile,AGP);

**Comment by jakebeal** [comment]
Fixed in https://github.com/jakebeal/TASBEFlowAnalytics/commit/a41b09f1fbf5c08b1af6ace26b6a807693cb5f16
